import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

function clean(value = '') {
  return String(value || '').trim().replace(/\/$/, '');
}

function jsString(value = '') {
  return JSON.stringify(String(value || ''));
}

const apiUrl = clean(process.env.VITE_API_URL || process.env.TYNA_BACKEND_URL || '');
const googleClientId = clean(process.env.VITE_GOOGLE_CLIENT_ID || process.env.GOOGLE_CLIENT_ID || '');
const paystackPublicKey = clean(process.env.VITE_PAYSTACK_PUBLIC_KEY || process.env.PAYSTACK_PUBLIC_KEY || '');
const whatsappNumber = clean(process.env.VITE_PUBLIC_WHATSAPP_NUMBER || process.env.PUBLIC_WHATSAPP_NUMBER || '');
const whatsappInternational = clean(process.env.VITE_PUBLIC_WHATSAPP_INTERNATIONAL || process.env.PUBLIC_WHATSAPP_INTERNATIONAL || '');
const usdNgnRate = clean(process.env.VITE_TYNA_USD_NGN_RATE || process.env.TYNA_USD_NGN_RATE || process.env.USD_NGN_RATE || '');
const adsenseClientId = clean(process.env.VITE_ADSENSE_CLIENT_ID || process.env.GOOGLE_ADSENSE_CLIENT_ID || process.env.ADSENSE_CLIENT_ID || '');

const output = `// This file is generated by frontend/scripts/write-config.js during the Vercel build.
// It is safe to expose these public frontend values. Do not put backend secrets here.
(function () {
  const LOCAL_API_URL = 'http://localhost:5000';
  const PRODUCTION_API_URL = window.TYNA_BACKEND_URL || ${jsString(apiUrl)} || location.origin;
  const isLocal =
    location.hostname === 'localhost' ||
    location.hostname === '127.0.0.1';

  window.TYNA_API_URL = isLocal
    ? LOCAL_API_URL
    : String(PRODUCTION_API_URL).replace(/\\/$/, '');

  window.TYNA_GOOGLE_CLIENT_ID = window.TYNA_GOOGLE_CLIENT_ID || ${jsString(googleClientId)};
  window.TYNA_PAYSTACK_PUBLIC_KEY = window.TYNA_PAYSTACK_PUBLIC_KEY || ${jsString(paystackPublicKey)};
  window.TYNA_PUBLIC_WHATSAPP_NUMBER = window.TYNA_PUBLIC_WHATSAPP_NUMBER || ${jsString(whatsappNumber)};
  window.TYNA_PUBLIC_WHATSAPP_INTERNATIONAL = window.TYNA_PUBLIC_WHATSAPP_INTERNATIONAL || ${jsString(whatsappInternational)};
  window.TYNA_USD_NGN_RATE = Number(window.TYNA_USD_NGN_RATE || ${jsString(usdNgnRate)});
  window.TYNA_ADSENSE_CLIENT_ID = window.TYNA_ADSENSE_CLIENT_ID || ${jsString(adsenseClientId)};
})();
`;

const file = resolve('assets/js/config.js');
mkdirSync(dirname(file), { recursive: true });
writeFileSync(file, output);
console.log(`Wrote ${file}`);

